# TODO feature (?)
default:
  multipleStables: false
  hookDir: hooks
  branches:
    master: master
    develop: dev
    release: release
    hotfixPrefix: hotfix-
  dirs:
    log: log
    errLog: log
    deployRoot: /var/www/test
